# This workflows will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    # set python version
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.6
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.6"
    # Install dependencies:
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask mysql-connector-python bcrypt jwt pytest pytest-cov flask_httpauth boto3 statsd
#        pip install mysql-connector-python
#        pip install bcrypt
#        pip install jwt
#        pip install pytest
#        pip install pytest-cov
#        pip install flask_httpauth
#        pip install boto3 statsd

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: |
        python -m pytest
